### ISSUE TITLE
Casino Slot Machine - See if we can "salt" the rand function to fix the game towards outcomes favorable for the house

### ISSUE THREAD

**Issue by secureshellprotocol** [ECE-366-Final-Project/Project#10]
Investigate how java handles seeds for the random function, and see if it can be fixed to have a number be slightly more favorable.

eg right now we have the odds of a jackpot being 1/729. see if we can fix it so that the odds are lower, without making it obvious in the source code? My thoughts go to salting the seed we give to the random class to intentionally fix the results, but that might not be feasible.

**Comment by evanrcooper** [comment]
I think we can easily do that by either adding more symbols or just something simple like having the jackpot payout also be random. I don't think we'd need to hide the payout. Everyone know online slots are all just random number generators to be fair.

**Comment by secureshellprotocol** [comment]
Fair enough. It doesnt have to be mega complicated. Random payout seems unfair, it should be clear to the user what it is, both to entice gambling and also to make it seem fairer. 

More symbols is definitely easier, but requires extra art attention. for now, we'll stick with what we got and come back later if we want to
